//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/commons-lang/src/main/java/org/apache/commons/lang3/time/DateParser.java
//

#include "J2ObjC_source.h"
#include "OrgApacheCommonsLang3TimeDateParser.h"

@interface OrgApacheCommonsLang3TimeDateParser : NSObject

@end

@implementation OrgApacheCommonsLang3TimeDateParser

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LJavaUtilDate;", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "LJavaUtilDate;", 0x401, 0, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 0, 4, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilTimeZone;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilLocale;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 5, 1, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 5, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(parseWithNSString:);
  methods[1].selector = @selector(parseWithNSString:withJavaTextParsePosition:);
  methods[2].selector = @selector(parseWithNSString:withJavaTextParsePosition:withJavaUtilCalendar:);
  methods[3].selector = @selector(getPattern);
  methods[4].selector = @selector(getTimeZone);
  methods[5].selector = @selector(getLocale);
  methods[6].selector = @selector(parseObjectWithNSString:);
  methods[7].selector = @selector(parseObjectWithNSString:withJavaTextParsePosition:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "parse", "LNSString;", "LJavaTextParseException;", "LNSString;LJavaTextParsePosition;", "LNSString;LJavaTextParsePosition;LJavaUtilCalendar;", "parseObject" };
  static const J2ObjcClassInfo _OrgApacheCommonsLang3TimeDateParser = { "DateParser", "org.apache.commons.lang3.time", ptrTable, methods, NULL, 7, 0x609, 8, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheCommonsLang3TimeDateParser;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheCommonsLang3TimeDateParser)
