//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/commons-lang/src/main/java/org/apache/commons/lang3/mutable/Mutable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsLang3MutableMutable")
#ifdef RESTRICT_OrgApacheCommonsLang3MutableMutable
#define INCLUDE_ALL_OrgApacheCommonsLang3MutableMutable 0
#else
#define INCLUDE_ALL_OrgApacheCommonsLang3MutableMutable 1
#endif
#undef RESTRICT_OrgApacheCommonsLang3MutableMutable

#if !defined (OrgApacheCommonsLang3MutableMutable_) && (INCLUDE_ALL_OrgApacheCommonsLang3MutableMutable || defined(INCLUDE_OrgApacheCommonsLang3MutableMutable))
#define OrgApacheCommonsLang3MutableMutable_

@protocol OrgApacheCommonsLang3MutableMutable < JavaObject >

- (id)getValue;

- (void)setValueWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsLang3MutableMutable)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsLang3MutableMutable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsLang3MutableMutable")
