//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/commons-lang/src/main/java/org/apache/commons/lang3/time/DatePrinter.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgApacheCommonsLang3TimeDatePrinter.h"
#include "java/lang/Deprecated.h"
#include "java/lang/annotation/Annotation.h"

@interface OrgApacheCommonsLang3TimeDatePrinter : NSObject

@end

__attribute__((unused)) static IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$0();

__attribute__((unused)) static IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$1();

__attribute__((unused)) static IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$2();

@implementation OrgApacheCommonsLang3TimeDatePrinter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 0, 2, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 0, 3, -1, -1, -1, -1 },
    { NULL, "LJavaLangStringBuffer;", 0x401, 0, 4, -1, -1, 5, -1 },
    { NULL, "LJavaLangStringBuffer;", 0x401, 0, 6, -1, -1, 7, -1 },
    { NULL, "LJavaLangStringBuffer;", 0x401, 0, 8, -1, -1, 9, -1 },
    { NULL, "LJavaLangAppendable;", 0x401, 0, 10, -1, 11, -1, -1 },
    { NULL, "LJavaLangAppendable;", 0x401, 0, 12, -1, 13, -1, -1 },
    { NULL, "LJavaLangAppendable;", 0x401, 0, 14, -1, 15, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilTimeZone;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilLocale;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaLangStringBuffer;", 0x401, 0, 16, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(formatWithLong:);
  methods[1].selector = @selector(formatWithJavaUtilDate:);
  methods[2].selector = @selector(formatWithJavaUtilCalendar:);
  methods[3].selector = @selector(formatWithLong:withJavaLangStringBuffer:);
  methods[4].selector = @selector(formatWithJavaUtilDate:withJavaLangStringBuffer:);
  methods[5].selector = @selector(formatWithJavaUtilCalendar:withJavaLangStringBuffer:);
  methods[6].selector = @selector(formatWithLong:withJavaLangAppendable:);
  methods[7].selector = @selector(formatWithJavaUtilDate:withJavaLangAppendable:);
  methods[8].selector = @selector(formatWithJavaUtilCalendar:withJavaLangAppendable:);
  methods[9].selector = @selector(getPattern);
  methods[10].selector = @selector(getTimeZone);
  methods[11].selector = @selector(getLocale);
  methods[12].selector = @selector(formatWithId:withJavaLangStringBuffer:withJavaTextFieldPosition:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "format", "J", "LJavaUtilDate;", "LJavaUtilCalendar;", "JLJavaLangStringBuffer;", (void *)&OrgApacheCommonsLang3TimeDatePrinter__Annotations$0, "LJavaUtilDate;LJavaLangStringBuffer;", (void *)&OrgApacheCommonsLang3TimeDatePrinter__Annotations$1, "LJavaUtilCalendar;LJavaLangStringBuffer;", (void *)&OrgApacheCommonsLang3TimeDatePrinter__Annotations$2, "JLJavaLangAppendable;", "<B::Ljava/lang/Appendable;>(JTB;)TB;", "LJavaUtilDate;LJavaLangAppendable;", "<B::Ljava/lang/Appendable;>(Ljava/util/Date;TB;)TB;", "LJavaUtilCalendar;LJavaLangAppendable;", "<B::Ljava/lang/Appendable;>(Ljava/util/Calendar;TB;)TB;", "LNSObject;LJavaLangStringBuffer;LJavaTextFieldPosition;" };
  static const J2ObjcClassInfo _OrgApacheCommonsLang3TimeDatePrinter = { "DatePrinter", "org.apache.commons.lang3.time", ptrTable, methods, NULL, 7, 0x609, 13, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheCommonsLang3TimeDatePrinter;
}

@end

IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgApacheCommonsLang3TimeDatePrinter__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheCommonsLang3TimeDatePrinter)
