//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/commons-lang/src/main/java/org/apache/commons/lang3/text/translate/package-info.java
//

#include "J2ObjC_source.h"
#include "OrgApacheCommonsLang3TextTranslatepackage-info.h"
