//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/experiments/InnerQueryTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest")
#ifdef RESTRICT_CoTouchlabSqueakyExperimentsInnerQueryTest
#define INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyExperimentsInnerQueryTest

#if !defined (CoTouchlabSqueakyExperimentsInnerQueryTest_) && (INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest || defined(INCLUDE_CoTouchlabSqueakyExperimentsInnerQueryTest))
#define CoTouchlabSqueakyExperimentsInnerQueryTest_

#define RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#define INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#include "CoTouchlabSqueakyFieldTypesBaseTypeTestHide.h"

@interface CoTouchlabSqueakyExperimentsInnerQueryTest : CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#pragma mark Public

- (instancetype)init;

- (void)after;

- (void)before;

- (void)testBigDecimal;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyExperimentsInnerQueryTest)

FOUNDATION_EXPORT void CoTouchlabSqueakyExperimentsInnerQueryTest_init(CoTouchlabSqueakyExperimentsInnerQueryTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest *new_CoTouchlabSqueakyExperimentsInnerQueryTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest *create_CoTouchlabSqueakyExperimentsInnerQueryTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyExperimentsInnerQueryTest)

#endif

#if !defined (CoTouchlabSqueakyExperimentsInnerQueryTest_Child_) && (INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest || defined(INCLUDE_CoTouchlabSqueakyExperimentsInnerQueryTest_Child))
#define CoTouchlabSqueakyExperimentsInnerQueryTest_Child_

@class CoTouchlabSqueakyExperimentsInnerQueryTest_Parent;
@class JavaLangLong;
@class JavaUtilDate;

@interface CoTouchlabSqueakyExperimentsInnerQueryTest_Child : NSObject {
 @public
  JavaLangLong *id__;
  NSString *someVal_;
  jint otherVal_;
  JavaUtilDate *moreWeight_;
  CoTouchlabSqueakyExperimentsInnerQueryTest_Parent *parent_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyExperimentsInnerQueryTest_Child)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Child, id__, JavaLangLong *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Child, someVal_, NSString *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Child, moreWeight_, JavaUtilDate *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Child, parent_, CoTouchlabSqueakyExperimentsInnerQueryTest_Parent *)

FOUNDATION_EXPORT void CoTouchlabSqueakyExperimentsInnerQueryTest_Child_init(CoTouchlabSqueakyExperimentsInnerQueryTest_Child *self);

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest_Child *new_CoTouchlabSqueakyExperimentsInnerQueryTest_Child_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest_Child *create_CoTouchlabSqueakyExperimentsInnerQueryTest_Child_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyExperimentsInnerQueryTest_Child)

#endif

#if !defined (CoTouchlabSqueakyExperimentsInnerQueryTest_Parent_) && (INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest || defined(INCLUDE_CoTouchlabSqueakyExperimentsInnerQueryTest_Parent))
#define CoTouchlabSqueakyExperimentsInnerQueryTest_Parent_

@interface CoTouchlabSqueakyExperimentsInnerQueryTest_Parent : NSObject {
 @public
  jlong id__;
  NSString *name_;
  NSString *category_;
  NSString *otherShit_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent, name_, NSString *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent, category_, NSString *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent, otherShit_, NSString *)

FOUNDATION_EXPORT void CoTouchlabSqueakyExperimentsInnerQueryTest_Parent_init(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent *self);

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest_Parent *new_CoTouchlabSqueakyExperimentsInnerQueryTest_Parent_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyExperimentsInnerQueryTest_Parent *create_CoTouchlabSqueakyExperimentsInnerQueryTest_Parent_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyExperimentsInnerQueryTest_Parent)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyExperimentsInnerQueryTest")
