//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/StringBytesTypeTest$LocalStringBytesUtf8$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration

#if !defined (CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration))
#define CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data;

- (CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)d1
                        withId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8 *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration, instance, CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_init(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *new_CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration *create_CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields))
#define CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_Enum_string = 0,
};

@interface CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_get_string();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields, string)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields *CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesStringBytesTypeTest_LocalStringBytesUtf8_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesStringBytesTypeTest$LocalStringBytesUtf8$Configuration")
