//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/BaseTypeTestHide.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#if !defined (CoTouchlabSqueakyFieldTypesBaseTypeTestHide_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide || defined(INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide))
#define CoTouchlabSqueakyFieldTypesBaseTypeTestHide_

#define RESTRICT_CoTouchlabSqueakySuperBaseTestHide 1
#define INCLUDE_CoTouchlabSqueakySuperBaseTestHide 1
#include "CoTouchlabSqueakySuperBaseTestHide.h"

@class CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper;
@class IOSObjectArray;

@interface CoTouchlabSqueakyFieldTypesBaseTypeTestHide : CoTouchlabSqueakySuperBaseTestHide

#pragma mark Public

- (instancetype)init;

- (CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *)createHelperWithIOSClassArray:(IOSObjectArray *)c;

- (CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *)createViewHelperWithNSString:(NSString *)viewSql
                                                                         withIOSClassArray:(IOSObjectArray *)c;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesBaseTypeTestHide)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesBaseTypeTestHide_init(CoTouchlabSqueakyFieldTypesBaseTypeTestHide *self);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesBaseTypeTestHide)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide || defined(INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper))
#define CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_

#define RESTRICT_CoTouchlabSqueakyDbSqliteSqueakyOpenHelper 1
#define INCLUDE_CoTouchlabSqueakyDbSqliteSqueakyOpenHelper 1
#include "CoTouchlabSqueakyDbSqliteSqueakyOpenHelper.h"

@class AndroidContentContext;
@class AndroidDatabaseSqliteSQLiteDatabase;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper : CoTouchlabSqueakyDbSqliteSqueakyOpenHelper

#pragma mark Public

- (instancetype)initWithAndroidContentContext:(AndroidContentContext *)context
                             withJavaUtilList:(id<JavaUtilList>)createSqlList
                                 withNSString:(NSString *)name
                            withIOSClassArray:(IOSObjectArray *)managingClasses;

- (instancetype)initWithAndroidContentContext:(AndroidContentContext *)context
                                 withNSString:(NSString *)name
                            withIOSClassArray:(IOSObjectArray *)managingClasses;

- (void)onCreateWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)sqLiteDatabase;

- (void)onUpgradeWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)sqLiteDatabase
                                                 withInt:(jint)oldVersion
                                                 withInt:(jint)newVersion;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withNSString_withIOSClassArray_(CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *self, AndroidContentContext *context, NSString *name, IOSObjectArray *managingClasses);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *new_CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withNSString_withIOSClassArray_(AndroidContentContext *context, NSString *name, IOSObjectArray *managingClasses) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *create_CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withNSString_withIOSClassArray_(AndroidContentContext *context, NSString *name, IOSObjectArray *managingClasses);

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withJavaUtilList_withNSString_withIOSClassArray_(CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *self, AndroidContentContext *context, id<JavaUtilList> createSqlList, NSString *name, IOSObjectArray *managingClasses);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *new_CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withJavaUtilList_withNSString_withIOSClassArray_(AndroidContentContext *context, id<JavaUtilList> createSqlList, NSString *name, IOSObjectArray *managingClasses) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper *create_CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper_initWithAndroidContentContext_withJavaUtilList_withNSString_withIOSClassArray_(AndroidContentContext *context, id<JavaUtilList> createSqlList, NSString *name, IOSObjectArray *managingClasses);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesBaseTypeTestHide_SimpleHelper)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBaseTypeTestHide")
