//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/FloatObjectTypeTest$LocalFloatObj$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration

#if !defined (CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration))
#define CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data;

- (CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)d1
                        withId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration, instance, CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_init(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *new_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration *create_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields))
#define CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_Enum_floatField = 0,
};

@interface CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_get_floatField();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields, floatField)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesFloatObjectTypeTest_LocalFloatObj_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesFloatObjectTypeTest$LocalFloatObj$Configuration")
