//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/BigDecimalStringTypeTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest

#if !defined (CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest))
#define CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest_

@interface CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)testCoverage;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest_init(CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest *new_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest *create_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesBigDecimalStringTypeTest")
