//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal$Configuration.java
//

#include "AndroidDatabaseCursor.h"
#include "CoTouchlabSqueakyDaoModelDao.h"
#include "CoTouchlabSqueakyDbSQLiteStatement.h"
#include "CoTouchlabSqueakyFieldDataType.h"
#include "CoTouchlabSqueakyFieldFieldType.h"
#include "CoTouchlabSqueakyFieldForeignCollectionInfo.h"
#include "CoTouchlabSqueakyFieldTypesBigDecimalTypeTest$NotBigDecimal$Configuration.h"
#include "CoTouchlabSqueakyFieldTypesBigDecimalTypeTest.h"
#include "CoTouchlabSqueakyTableTableInfo.h"
#include "CoTouchlabSqueakyTableTransientCache.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields () {
 @public
  CoTouchlabSqueakyFieldFieldType *fieldType_;
}

@end

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields, fieldType_, CoTouchlabSqueakyFieldFieldType *)

__attribute__((unused)) static void CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration)

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_instance;

@implementation CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *data = create_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_init();
  return data;
}

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache {
  JreStrongAssign(&((CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *) nil_chk(data))->bigDecimal_, [((id<AndroidDatabaseCursor>) nil_chk(results)) getStringWithInt:0]);
}

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data
                withId:(id)val {
}

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data {
  return nil;
}

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data {
  NSString *val1 = ((CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *) nil_chk(data))->bigDecimal_;
  if (val1 == nil) {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindNullWithInt:1];
  }
  else {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindStringWithInt:1 withNSString:data->bigDecimal_];
  }
}

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data {
  NSString *val1 = ((CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *) nil_chk(data))->bigDecimal_;
  if (val1 == nil) {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindNullWithInt:1];
  }
  else {
    [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindStringWithInt:1 withNSString:data->bigDecimal_];
  }
}

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data {
  return @"heyo";
}

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)d1
                        withId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)d2 {
  return false;
}

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName {
}

+ (IOSObjectArray *)getFields {
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getFields();
}

+ (IOSObjectArray *)getForeignConfigs {
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getForeignConfigs();
}

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig {
  CoTouchlabSqueakyTableTableInfo *config = create_CoTouchlabSqueakyTableTableInfo_initWithIOSClass_withNSString_withCoTouchlabSqueakyFieldFieldsEnumArray_withCoTouchlabSqueakyFieldForeignCollectionInfoArray_(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_class_(), @"LocalBigDecimal", CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getFields(), CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getForeignConfigs());
  return config;
}

- (void)dealloc {
  RELEASE_(fields_);
  RELEASE_(foreignConfigs_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, 2, 5, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 11, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 13, 9, 2, -1, -1, -1 },
    { NULL, "Z", 0x1, 14, 15, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 17, 2, 18, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldFieldsEnum;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyTableTableInfo;", 0x1, -1, -1, 2, 19, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(createObjectWithAndroidDatabaseCursor:);
  methods[2].selector = @selector(fillRowWithId:withAndroidDatabaseCursor:withCoTouchlabSqueakyDaoModelDao:withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:withCoTouchlabSqueakyTableTransientCache:);
  methods[3].selector = @selector(assignIdWithId:withId:);
  methods[4].selector = @selector(extractIdWithId:);
  methods[5].selector = @selector(bindValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[6].selector = @selector(bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[7].selector = @selector(objectToStringWithId:);
  methods[8].selector = @selector(objectsEqualWithId:withId:);
  methods[9].selector = @selector(fillForeignCollectionWithId:withCoTouchlabSqueakyDaoModelDao:withNSString:);
  methods[10].selector = @selector(getFields);
  methods[11].selector = @selector(getForeignConfigs);
  methods[12].selector = @selector(getTableConfig);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "instance", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration;", .constantValue.asLong = 0, 0x19, -1, 20, -1, -1 },
    { "fields_", "[LCoTouchlabSqueakyFieldFieldsEnum;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "foreignConfigs_", "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "createObject", "LAndroidDatabaseCursor;", "LJavaSqlSQLException;", "fillRow", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;LAndroidDatabaseCursor;LCoTouchlabSqueakyDaoModelDao;[LCoTouchlabSqueakyDaoDao_ForeignRefresh;LCoTouchlabSqueakyTableTransientCache;", "(Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;Landroid/database/Cursor;Lco/touchlab/squeaky/dao/ModelDao<Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;>;[Lco/touchlab/squeaky/dao/Dao$ForeignRefresh;Lco/touchlab/squeaky/table/TransientCache;)V", "assignId", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;LNSObject;", "extractId", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;", "bindVals", "LCoTouchlabSqueakyDbSQLiteStatement;LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;", "bindCreateVals", "objectToString", "objectsEqual", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;", "fillForeignCollection", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal;LCoTouchlabSqueakyDaoModelDao;LNSString;", "(Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;Lco/touchlab/squeaky/dao/ModelDao<Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;>;Ljava/lang/String;)V", "()Lco/touchlab/squeaky/table/TableInfo<Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;>;", &CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_instance, "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields;", "Ljava/lang/Object;Lco/touchlab/squeaky/table/GeneratedTableMapper<Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal;>;" };
  static const J2ObjcClassInfo _CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration = { "BigDecimalTypeTest$NotBigDecimal$Configuration", "co.touchlab.squeaky.field.types", ptrTable, methods, fields, 7, 0x11, 13, 3, -1, 21, -1, 22, -1 };
  return &_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration;
}

+ (void)initialize {
  if (self == [CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration class]) {
    JreStrongAssignAndConsume(&CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_instance, new_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_init());
    J2OBJC_SET_INITIALIZED(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration)
  }
}

@end

void CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_init(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration *self) {
  NSObject_init(self);
  JreStrongAssign(&self->fields_, CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getFields());
  JreStrongAssign(&self->foreignConfigs_, CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getForeignConfigs());
}

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration *new_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_init() {
  J2OBJC_NEW_IMPL(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration, init)
}

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration *create_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_init() {
  J2OBJC_CREATE_IMPL(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration, init)
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getFields() {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_initialize();
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values();
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_getForeignConfigs() {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_initialize();
  id<JavaUtilList> list = create_JavaUtilArrayList_init();
  CoTouchlabSqueakyFieldForeignCollectionInfo *config = nil;
  return [list toArrayWithNSObjectArray:[IOSObjectArray arrayWithLength:[list size] type:CoTouchlabSqueakyFieldForeignCollectionInfo_class_()]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration)

J2OBJC_INITIALIZED_DEFN(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields)

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values_[1];

@implementation CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields

- (CoTouchlabSqueakyFieldFieldType *)getFieldType {
  return fieldType_;
}

+ (IOSObjectArray *)values {
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values();
}

+ (CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *)valueOfWithNSString:(NSString *)name {
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LCoTouchlabSqueakyFieldFieldType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getFieldType);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "bigDecimal", "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "fieldType_", "LCoTouchlabSqueakyFieldFieldType;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields, bigDecimal), "LCoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration;", "Ljava/lang/Enum<Lco/touchlab/squeaky/field/types/BigDecimalTypeTest$NotBigDecimal$Configuration$Fields;>;Lco/touchlab/squeaky/field/FieldsEnum;" };
  static const J2ObjcClassInfo _CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields = { "Fields", "co.touchlab.squeaky.field.types", ptrTable, methods, fields, 7, 0x4019, 3, 2, 3, -1, -1, 4, -1 };
  return &_CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields;
}

+ (void)initialize {
  if (self == [CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 1 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields, bigDecimal) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"LocalBigDecimal", @"bigDecimal", @"bigDecimal", false, false, false, JreLoadEnum(CoTouchlabSqueakyFieldDataType, STRING), NSString_class_(), true, nil, false, false, false, false, nil, nil, nil, false), @"bigDecimal", 0);
    J2OBJC_SET_INITIALIZED(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields)
  }
}

@end

void CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  JreStrongAssign(&self->fieldType_, fieldType);
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values() {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initialize();
  return [IOSObjectArray arrayWithObjects:CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values_ count:1 type:CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_class_()];
}

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_valueOfWithNSString_(NSString *name) {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initialize();
  for (int i = 0; i < 1; i++) {
    CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *e = CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields *CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_fromOrdinal(NSUInteger ordinal) {
  CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_initialize();
  if (ordinal >= 1) {
    return nil;
  }
  return CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyFieldTypesBigDecimalTypeTest_NotBigDecimal_Configuration_Fields)
