//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/stmt/JoinTest$Foo$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration

#if !defined (CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration || defined(INCLUDE_CoTouchlabSqueakyStmtJoinTest_Foo_Configuration))
#define CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyStmtJoinTest_Foo;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@class JavaLangInteger;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyStmtJoinTest_Foo_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data;

- (CoTouchlabSqueakyStmtJoinTest_Foo *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (JavaLangInteger *)extractIdWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)d1
                        withId:(CoTouchlabSqueakyStmtJoinTest_Foo *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyStmtJoinTest_Foo *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration, instance, CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_init(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *new_CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration *create_CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration)

@compatibility_alias CoTouchlabSqueakyStmtJoinTest$Foo$Configuration CoTouchlabSqueakyStmtJoinTest_Foo_Configuration;

#endif

#if !defined (CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration || defined(INCLUDE_CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields))
#define CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum) {
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_id = 0,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_name = 1,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_ival = 2,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_lval = 3,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_dval = 4,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_fval = 5,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_sDate = 6,
  CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_Enum_lDate = 7,
};

@interface CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_values_[];

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_id();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, id)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_name();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, name)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_ival();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, ival)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_lval();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, lval)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_dval();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, dval)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_fval();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, fval)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_sDate();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, sDate)

inline CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_get_lDate();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields, lDate)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields *CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyStmtJoinTest_Foo_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyStmtJoinTest$Foo$Configuration")
