//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/ForeignFieldRefreshTest$Child$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration

#if !defined (CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration))
#define CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@class JavaLangInteger;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data;

- (CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (JavaLangInteger *)extractIdWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)d1
                        withId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration, instance, CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_init(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *new_CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration *create_CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields))
#define CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_Enum_id = 0,
  CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_Enum_asdf = 1,
  CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_Enum_parentLazy = 2,
  CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_Enum_parentEager = 3,
};

@interface CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_get_id();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields, id)

inline CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_get_asdf();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields, asdf)

inline CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_get_parentLazy();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields, parentLazy)

inline CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_get_parentEager();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields, parentEager)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields *CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignFieldRefreshTest_Child_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignFieldRefreshTest$Child$Configuration")
