//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/dao/DaoTest$Bar$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration

#if !defined (CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration || defined(INCLUDE_CoTouchlabSqueakyDaoDaoTest_Bar_Configuration))
#define CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoDaoTest_Bar;
@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@class JavaLangInteger;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyDaoDaoTest_Bar_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data;

- (CoTouchlabSqueakyDaoDaoTest_Bar *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (JavaLangInteger *)extractIdWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)d1
                        withId:(CoTouchlabSqueakyDaoDaoTest_Bar *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyDaoDaoTest_Bar *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration, instance, CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_init(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *new_CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration *create_CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration)

@compatibility_alias CoTouchlabSqueakyDaoDaoTest$Bar$Configuration CoTouchlabSqueakyDaoDaoTest_Bar_Configuration;

#endif

#if !defined (CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration || defined(INCLUDE_CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields))
#define CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_Enum) {
  CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_Enum_id = 0,
  CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_Enum_name = 1,
};

@interface CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_values_[];

inline CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_get_id();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields, id)

inline CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_get_name();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields, name)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields *CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyDaoDaoTest_Bar_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyDaoDaoTest$Bar$Configuration")
