//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/ShortTypeTest$LocalShort$Configuration.java
//

#include "AndroidDatabaseCursor.h"
#include "CoTouchlabSqueakyDaoModelDao.h"
#include "CoTouchlabSqueakyDbSQLiteStatement.h"
#include "CoTouchlabSqueakyFieldDataType.h"
#include "CoTouchlabSqueakyFieldFieldType.h"
#include "CoTouchlabSqueakyFieldForeignCollectionInfo.h"
#include "CoTouchlabSqueakyFieldTypesShortTypeTest$LocalShort$Configuration.h"
#include "CoTouchlabSqueakyFieldTypesShortTypeTest.h"
#include "CoTouchlabSqueakyTableTableInfo.h"
#include "CoTouchlabSqueakyTableTransientCache.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields () {
 @public
  CoTouchlabSqueakyFieldFieldType *fieldType_;
}

@end

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields, fieldType_, CoTouchlabSqueakyFieldFieldType *)

__attribute__((unused)) static void CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration)

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_instance;

@implementation CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *data = create_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_init();
  return data;
}

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache {
  if (![((id<AndroidDatabaseCursor>) nil_chk(results)) isNullWithInt:0]) ((CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *) nil_chk(data))->shortField_ = [results getShortWithInt:0];
}

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data
                withId:(id)val {
}

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data {
  return nil;
}

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data {
  [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindLongWithInt:1 withLong:((CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *) nil_chk(data))->shortField_];
}

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data {
  [((id<CoTouchlabSqueakyDbSQLiteStatement>) nil_chk(stmt)) bindLongWithInt:1 withLong:((CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *) nil_chk(data))->shortField_];
}

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data {
  return @"heyo";
}

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)d1
                        withId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)d2 {
  return false;
}

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName {
}

+ (IOSObjectArray *)getFields {
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getFields();
}

+ (IOSObjectArray *)getForeignConfigs {
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getForeignConfigs();
}

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig {
  CoTouchlabSqueakyTableTableInfo *config = create_CoTouchlabSqueakyTableTableInfo_initWithIOSClass_withNSString_withCoTouchlabSqueakyFieldFieldsEnumArray_withCoTouchlabSqueakyFieldForeignCollectionInfoArray_(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_class_(), @"com_j256_ormlite_field_types_ShortTypeTest_LocalShort", CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getFields(), CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getForeignConfigs());
  return config;
}

- (void)dealloc {
  RELEASE_(fields_);
  RELEASE_(foreignConfigs_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, 2, 5, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 11, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 13, 9, 2, -1, -1, -1 },
    { NULL, "Z", 0x1, 14, 15, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 17, 2, 18, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldFieldsEnum;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyTableTableInfo;", 0x1, -1, -1, 2, 19, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(createObjectWithAndroidDatabaseCursor:);
  methods[2].selector = @selector(fillRowWithId:withAndroidDatabaseCursor:withCoTouchlabSqueakyDaoModelDao:withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:withCoTouchlabSqueakyTableTransientCache:);
  methods[3].selector = @selector(assignIdWithId:withId:);
  methods[4].selector = @selector(extractIdWithId:);
  methods[5].selector = @selector(bindValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[6].selector = @selector(bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:withId:);
  methods[7].selector = @selector(objectToStringWithId:);
  methods[8].selector = @selector(objectsEqualWithId:withId:);
  methods[9].selector = @selector(fillForeignCollectionWithId:withCoTouchlabSqueakyDaoModelDao:withNSString:);
  methods[10].selector = @selector(getFields);
  methods[11].selector = @selector(getForeignConfigs);
  methods[12].selector = @selector(getTableConfig);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "instance", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration;", .constantValue.asLong = 0, 0x19, -1, 20, -1, -1 },
    { "fields_", "[LCoTouchlabSqueakyFieldFieldsEnum;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "foreignConfigs_", "[LCoTouchlabSqueakyFieldForeignCollectionInfo;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "createObject", "LAndroidDatabaseCursor;", "LJavaSqlSQLException;", "fillRow", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;LAndroidDatabaseCursor;LCoTouchlabSqueakyDaoModelDao;[LCoTouchlabSqueakyDaoDao_ForeignRefresh;LCoTouchlabSqueakyTableTransientCache;", "(Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;Landroid/database/Cursor;Lco/touchlab/squeaky/dao/ModelDao<Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;>;[Lco/touchlab/squeaky/dao/Dao$ForeignRefresh;Lco/touchlab/squeaky/table/TransientCache;)V", "assignId", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;LNSObject;", "extractId", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;", "bindVals", "LCoTouchlabSqueakyDbSQLiteStatement;LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;", "bindCreateVals", "objectToString", "objectsEqual", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;", "fillForeignCollection", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort;LCoTouchlabSqueakyDaoModelDao;LNSString;", "(Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;Lco/touchlab/squeaky/dao/ModelDao<Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;>;Ljava/lang/String;)V", "()Lco/touchlab/squeaky/table/TableInfo<Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;>;", &CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_instance, "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields;", "Ljava/lang/Object;Lco/touchlab/squeaky/table/GeneratedTableMapper<Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort;>;" };
  static const J2ObjcClassInfo _CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration = { "ShortTypeTest$LocalShort$Configuration", "co.touchlab.squeaky.field.types", ptrTable, methods, fields, 7, 0x11, 13, 3, -1, 21, -1, 22, -1 };
  return &_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration;
}

+ (void)initialize {
  if (self == [CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration class]) {
    JreStrongAssignAndConsume(&CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_instance, new_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_init());
    J2OBJC_SET_INITIALIZED(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration)
  }
}

@end

void CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_init(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration *self) {
  NSObject_init(self);
  JreStrongAssign(&self->fields_, CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getFields());
  JreStrongAssign(&self->foreignConfigs_, CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getForeignConfigs());
}

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration *new_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_init() {
  J2OBJC_NEW_IMPL(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration, init)
}

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration *create_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_init() {
  J2OBJC_CREATE_IMPL(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration, init)
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getFields() {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_initialize();
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values();
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_getForeignConfigs() {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_initialize();
  id<JavaUtilList> list = create_JavaUtilArrayList_init();
  CoTouchlabSqueakyFieldForeignCollectionInfo *config = nil;
  return [list toArrayWithNSObjectArray:[IOSObjectArray arrayWithLength:[list size] type:CoTouchlabSqueakyFieldForeignCollectionInfo_class_()]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration)

J2OBJC_INITIALIZED_DEFN(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields)

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values_[1];

@implementation CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields

- (CoTouchlabSqueakyFieldFieldType *)getFieldType {
  return fieldType_;
}

+ (IOSObjectArray *)values {
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values();
}

+ (CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *)valueOfWithNSString:(NSString *)name {
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LCoTouchlabSqueakyFieldFieldType;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getFieldType);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "shortField", "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "fieldType_", "LCoTouchlabSqueakyFieldFieldType;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields, shortField), "LCoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration;", "Ljava/lang/Enum<Lco/touchlab/squeaky/field/types/ShortTypeTest$LocalShort$Configuration$Fields;>;Lco/touchlab/squeaky/field/FieldsEnum;" };
  static const J2ObjcClassInfo _CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields = { "Fields", "co.touchlab.squeaky.field.types", ptrTable, methods, fields, 7, 0x4019, 3, 2, 3, -1, -1, 4, -1 };
  return &_CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields;
}

+ (void)initialize {
  if (self == [CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 1 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    (JreEnum(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields, shortField) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
    CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(e, create_CoTouchlabSqueakyFieldFieldType_initWithNSString_withNSString_withNSString_withBoolean_withBoolean_withBoolean_withCoTouchlabSqueakyFieldDataType_withIOSClass_withBoolean_withNSString_withBoolean_withBoolean_withBoolean_withBoolean_withNSString_withNSString_withNSString_withBoolean_(@"com_j256_ormlite_field_types_ShortTypeTest_LocalShort", @"shortField", @"shortField", false, false, false, JreLoadEnum(CoTouchlabSqueakyFieldDataType, SHORT), [IOSClass shortClass], true, nil, false, false, false, false, nil, nil, nil, false), @"shortField", 0);
    J2OBJC_SET_INITIALIZED(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields)
  }
}

@end

void CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initWithCoTouchlabSqueakyFieldFieldType_withNSString_withInt_(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *self, CoTouchlabSqueakyFieldFieldType *fieldType, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  JreStrongAssign(&self->fieldType_, fieldType);
}

IOSObjectArray *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values() {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initialize();
  return [IOSObjectArray arrayWithObjects:CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values_ count:1 type:CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_class_()];
}

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_valueOfWithNSString_(NSString *name) {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initialize();
  for (int i = 0; i < 1; i++) {
    CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *e = CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields *CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_fromOrdinal(NSUInteger ordinal) {
  CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_initialize();
  if (ordinal >= 1) {
    return nil;
  }
  return CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(CoTouchlabSqueakyFieldTypesShortTypeTest_LocalShort_Configuration_Fields)
