//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/FieldTypeTestHide.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldFieldTypeTestHide")
#ifdef RESTRICT_CoTouchlabSqueakyFieldFieldTypeTestHide
#define INCLUDE_ALL_CoTouchlabSqueakyFieldFieldTypeTestHide 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldFieldTypeTestHide 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldFieldTypeTestHide

#if !defined (CoTouchlabSqueakyFieldFieldTypeTestHide_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldFieldTypeTestHide || defined(INCLUDE_CoTouchlabSqueakyFieldFieldTypeTestHide))
#define CoTouchlabSqueakyFieldFieldTypeTestHide_

@interface CoTouchlabSqueakyFieldFieldTypeTestHide : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldFieldTypeTestHide)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldFieldTypeTestHide_init(CoTouchlabSqueakyFieldFieldTypeTestHide *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldFieldTypeTestHide *new_CoTouchlabSqueakyFieldFieldTypeTestHide_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldFieldTypeTestHide *create_CoTouchlabSqueakyFieldFieldTypeTestHide_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldFieldTypeTestHide)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldFieldTypeTestHide")
