//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/ByteArrayTypeTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesByteArrayTypeTest
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesByteArrayTypeTest

#if !defined (CoTouchlabSqueakyFieldTypesByteArrayTypeTest_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesByteArrayTypeTest))
#define CoTouchlabSqueakyFieldTypesByteArrayTypeTest_

#define RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#define INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#include "CoTouchlabSqueakyFieldTypesBaseTypeTestHide.h"

@interface CoTouchlabSqueakyFieldTypesByteArrayTypeTest : CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#pragma mark Public

- (instancetype)init;

- (void)after;

- (void)before;

- (void)testByteArray;

- (void)testByteArrayNull;

- (void)testByteArrayParseDefault;

- (void)testCoverage;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesByteArrayTypeTest)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesByteArrayTypeTest_init(CoTouchlabSqueakyFieldTypesByteArrayTypeTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteArrayTypeTest *new_CoTouchlabSqueakyFieldTypesByteArrayTypeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteArrayTypeTest *create_CoTouchlabSqueakyFieldTypesByteArrayTypeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesByteArrayTypeTest)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray))
#define CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray_

@class IOSByteArray;

@interface CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray : NSObject {
 @public
  IOSByteArray *byteField_;
}

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray, byteField_, IOSByteArray *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray_init(CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray *new_CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray *create_CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesByteArrayTypeTest_LocalByteArray)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteArrayTypeTest")
