//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/DoubleObjectTypeTest$LocalDoubleObj$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration

#if !defined (CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration))
#define CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data;

- (CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)d1
                        withId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration, instance, CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_init(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *new_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration *create_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields))
#define CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_Enum_doubleField = 0,
};

@interface CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_get_doubleField();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields, doubleField)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields *CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest_LocalDoubleObj_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesDoubleObjectTypeTest$LocalDoubleObj$Configuration")
