//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/SerializableTypeTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesSerializableTypeTest
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesSerializableTypeTest

#if !defined (CoTouchlabSqueakyFieldTypesSerializableTypeTest_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesSerializableTypeTest))
#define CoTouchlabSqueakyFieldTypesSerializableTypeTest_

#define RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#define INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#include "CoTouchlabSqueakyFieldTypesBaseTypeTestHide.h"

@interface CoTouchlabSqueakyFieldTypesSerializableTypeTest : CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#pragma mark Public

- (instancetype)init;

- (void)after;

- (void)before;

- (void)testCoverage;

- (void)testSerializable;

- (void)testSerializableNull;

- (void)testSerializableParseDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesSerializableTypeTest)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesSerializableTypeTest_init(CoTouchlabSqueakyFieldTypesSerializableTypeTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesSerializableTypeTest *new_CoTouchlabSqueakyFieldTypesSerializableTypeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesSerializableTypeTest *create_CoTouchlabSqueakyFieldTypesSerializableTypeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesSerializableTypeTest)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable))
#define CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable_

@class JavaLangInteger;

@interface CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable : NSObject {
 @public
  JavaLangInteger *serializable_;
}

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable, serializable_, JavaLangInteger *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable_init(CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable *new_CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable *create_CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesSerializableTypeTest_LocalSerializable)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesSerializableTypeTest")
