//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/EnumStringTypeTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesEnumStringTypeTest
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesEnumStringTypeTest

#if !defined (CoTouchlabSqueakyFieldTypesEnumStringTypeTest_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesEnumStringTypeTest))
#define CoTouchlabSqueakyFieldTypesEnumStringTypeTest_

#define RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#define INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#include "CoTouchlabSqueakyFieldTypesBaseTypeTestHide.h"

@interface CoTouchlabSqueakyFieldTypesEnumStringTypeTest : CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#pragma mark Public

- (instancetype)init;

- (void)after;

- (void)before;

- (void)testCoverage;

- (void)testEnumString;

- (void)testEnumStringNull;

- (void)testUnknownEnumValue;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesEnumStringTypeTest)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesEnumStringTypeTest_init(CoTouchlabSqueakyFieldTypesEnumStringTypeTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest *new_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest *create_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesEnumStringTypeTest)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString))
#define CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString_

@class CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum;

@interface CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString : NSObject {
 @public
  CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *ourEnum_;
}

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString, ourEnum_, CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString_init(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString *new_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString *create_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_LocalEnumString)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum))
#define CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_Enum) {
  CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_Enum_FIRST = 0,
  CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_Enum_SECOND = 1,
};

@interface CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum : JavaLangEnum < NSCopying >

#pragma mark Public

+ (CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_values_[];

inline CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_get_FIRST();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum, FIRST)

inline CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_get_SECOND();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum, SECOND)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum *CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesEnumStringTypeTest_OurEnum)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesEnumStringTypeTest")
