//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/ForeignCollectionTest$ChildOrder$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration

#if !defined (CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration))
#define CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@class JavaLangInteger;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data;

- (CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (JavaLangInteger *)extractIdWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)d1
                        withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration, instance, CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_init(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *new_CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration *create_CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields))
#define CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_Enum_id = 0,
  CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_Enum_asdf = 1,
  CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_Enum_parent = 2,
};

@interface CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_get_id();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields, id)

inline CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_get_asdf();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields, asdf)

inline CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_get_parent();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields, parent)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignCollectionTest_ChildOrder_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ChildOrder$Configuration")
