//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/co/touchlab/squeaky/field/types/LongObjectTypeTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesLongObjectTypeTest
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesLongObjectTypeTest

#if !defined (CoTouchlabSqueakyFieldTypesLongObjectTypeTest_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesLongObjectTypeTest))
#define CoTouchlabSqueakyFieldTypesLongObjectTypeTest_

#define RESTRICT_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#define INCLUDE_CoTouchlabSqueakyFieldTypesBaseTypeTestHide 1
#include "CoTouchlabSqueakyFieldTypesBaseTypeTestHide.h"

@interface CoTouchlabSqueakyFieldTypesLongObjectTypeTest : CoTouchlabSqueakyFieldTypesBaseTypeTestHide

#pragma mark Public

- (instancetype)init;

- (void)after;

- (void)before;

- (void)testLongObj;

- (void)testLongObjNull;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesLongObjectTypeTest)

inline NSString *CoTouchlabSqueakyFieldTypesLongObjectTypeTest_get_TABLE_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CoTouchlabSqueakyFieldTypesLongObjectTypeTest_TABLE_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesLongObjectTypeTest, TABLE_NAME, NSString *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesLongObjectTypeTest_init(CoTouchlabSqueakyFieldTypesLongObjectTypeTest *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesLongObjectTypeTest *new_CoTouchlabSqueakyFieldTypesLongObjectTypeTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesLongObjectTypeTest *create_CoTouchlabSqueakyFieldTypesLongObjectTypeTest_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesLongObjectTypeTest)

#endif

#if !defined (CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest || defined(INCLUDE_CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj))
#define CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj_

@class JavaLangLong;

@interface CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj : NSObject {
 @public
  JavaLangLong *longField_;
}

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj, longField_, JavaLangLong *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj_init(CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj *new_CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj *create_CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj_init();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesLongObjectTypeTest_LocalLongObj)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesLongObjectTypeTest")
