//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/ForeignCollectionTest$ParentString$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration

#if !defined (CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration))
#define CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldForeignCollectionTest_ParentString;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data;

- (CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (NSString *)extractIdWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data;

- (void)fill_childrenWithCoTouchlabSqueakyFieldForeignCollectionTest_ParentString:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data
                                                 withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)d1
                        withId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration, instance, CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_init(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *new_CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration *create_CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields))
#define CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_Enum_id = 0,
  CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_Enum_name = 1,
};

@interface CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_get_id();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields, id)

inline CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_get_name();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields, name)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields *CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldForeignCollectionTest_ParentString_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldForeignCollectionTest$ParentString$Configuration")
