//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/build/generated/source/apt/test/co/touchlab/squeaky/field/types/ByteTypeTest$LocalByte$Configuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration")
#ifdef RESTRICT_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration 0
#else
#define INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration 1
#endif
#undef RESTRICT_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration

#if !defined (CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration))
#define CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_

#define RESTRICT_CoTouchlabSqueakyTableGeneratedTableMapper 1
#define INCLUDE_CoTouchlabSqueakyTableGeneratedTableMapper 1
#include "CoTouchlabSqueakyTableGeneratedTableMapper.h"

@class CoTouchlabSqueakyDaoModelDao;
@class CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte;
@class CoTouchlabSqueakyTableTableInfo;
@class CoTouchlabSqueakyTableTransientCache;
@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol CoTouchlabSqueakyDbSQLiteStatement;

@interface CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration : NSObject < CoTouchlabSqueakyTableGeneratedTableMapper > {
 @public
  IOSObjectArray *fields_;
  IOSObjectArray *foreignConfigs_;
}

#pragma mark Public

- (instancetype)init;

- (void)assignIdWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data
                withId:(id)val;

- (void)bindCreateValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                      withId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data;

- (void)bindValsWithCoTouchlabSqueakyDbSQLiteStatement:(id<CoTouchlabSqueakyDbSQLiteStatement>)stmt
                                                withId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data;

- (CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)createObjectWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results;

- (id)extractIdWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data;

- (void)fillForeignCollectionWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data
   withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
                       withNSString:(NSString *)fieldName;

- (void)fillRowWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data
withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)results
withCoTouchlabSqueakyDaoModelDao:(CoTouchlabSqueakyDaoModelDao *)modelDao
withCoTouchlabSqueakyDaoDao_ForeignRefreshArray:(IOSObjectArray *)foreignRefreshMap
withCoTouchlabSqueakyTableTransientCache:(CoTouchlabSqueakyTableTransientCache *)objectCache;

+ (IOSObjectArray *)getFields;

+ (IOSObjectArray *)getForeignConfigs;

- (CoTouchlabSqueakyTableTableInfo *)getTableConfig;

- (jboolean)objectsEqualWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)d1
                        withId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)d2;

- (NSString *)objectToStringWithId:(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte *)data;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration)

J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration, fields_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration, foreignConfigs_, IOSObjectArray *)

inline CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_get_instance();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration, instance, CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *)

FOUNDATION_EXPORT void CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_init(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *self);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *new_CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration *create_CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_init();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_getFields();

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_getForeignConfigs();

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration)

@compatibility_alias CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration;

#endif

#if !defined (CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_) && (INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration || defined(INCLUDE_CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields))
#define CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_CoTouchlabSqueakyFieldFieldsEnum 1
#define INCLUDE_CoTouchlabSqueakyFieldFieldsEnum 1
#include "CoTouchlabSqueakyFieldFieldsEnum.h"

@class CoTouchlabSqueakyFieldFieldType;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_Enum) {
  CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_Enum_byteField = 0,
};

@interface CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields : JavaLangEnum < NSCopying, CoTouchlabSqueakyFieldFieldsEnum >

#pragma mark Public

- (CoTouchlabSqueakyFieldFieldType *)getFieldType;

+ (CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_values_[];

inline CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_get_byteField();
J2OBJC_ENUM_CONSTANT(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields, byteField)

FOUNDATION_EXPORT IOSObjectArray *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_values();

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields *CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabSqueakyFieldTypesByteTypeTest_LocalByte_Configuration_Fields)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabSqueakyFieldTypesByteTypeTest$LocalByte$Configuration")
