//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/test/java/OneTestRunner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OneTestRunner")
#ifdef RESTRICT_OneTestRunner
#define INCLUDE_ALL_OneTestRunner 0
#else
#define INCLUDE_ALL_OneTestRunner 1
#endif
#undef RESTRICT_OneTestRunner

#if !defined (OneTestRunner_) && (INCLUDE_ALL_OneTestRunner || defined(INCLUDE_OneTestRunner))
#define OneTestRunner_

@interface OneTestRunner : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)runTests;

@end

J2OBJC_STATIC_INIT(OneTestRunner)

FOUNDATION_EXPORT void OneTestRunner_init(OneTestRunner *self);

FOUNDATION_EXPORT OneTestRunner *new_OneTestRunner_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OneTestRunner *create_OneTestRunner_init();

FOUNDATION_EXPORT void OneTestRunner_runTests();

J2OBJC_TYPE_LITERAL_HEADER(OneTestRunner)

#endif

#pragma pop_macro("INCLUDE_ALL_OneTestRunner")
