//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/Squeaky-doppl/tests/src/main/java/Dummy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Dummy")
#ifdef RESTRICT_Dummy
#define INCLUDE_ALL_Dummy 0
#else
#define INCLUDE_ALL_Dummy 1
#endif
#undef RESTRICT_Dummy

#if !defined (Dummy_) && (INCLUDE_ALL_Dummy || defined(INCLUDE_Dummy))
#define Dummy_

@interface Dummy : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(Dummy)

FOUNDATION_EXPORT void Dummy_init(Dummy *self);

FOUNDATION_EXPORT Dummy *new_Dummy_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Dummy *create_Dummy_init();

J2OBJC_TYPE_LITERAL_HEADER(Dummy)

#endif

#pragma pop_macro("INCLUDE_ALL_Dummy")
